"use client";

import {
  Avocado,
  Baby,
  BeerBottle,
  BeerStein,
  Bird,
  BowlFood,
  BowlSteam,
  Brandy,
  Bread,
  Cake,
  CallBell,
  Carrot,
  Champagne,
  Cheese,
  ChefHat,
  Cherries,
  Coffee,
  CoffeeBean,
  Cookie,
  CookingPot,
  Cow,
  Crown,
  Drop,
  Egg,
  EggCrack,
  Fire,
  Fish,
  FishSimple,
  Flame,
  Flask,
  ForkKnife,
  Gift,
  Grains,
  Hamburger,
  Heart,
  IceCream,
  Jar,
  JarLabel,
  Knife,
  Leaf,
  Martini,
  Orange,
  OrangeSlice,
  Pepper,
  PintGlass,
  Pizza,
  Plant,
  Popcorn,
  Popsicle,
  Shrimp,
  Snowflake,
  Sparkle,
  Star,
  Sun,
  TeaBag,
  Tray,
  TreePalm,
  Waves,
  Wine,
  type Icon,
} from "@phosphor-icons/react";
import type { CategoryIconId } from "@/lib/category-icons";

export const CATEGORY_ICON_COMPONENTS: Record<CategoryIconId, Icon> = {
  "fork-knife": ForkKnife,
  "cooking-pot": CookingPot,
  "bowl-steam": BowlSteam,
  "bowl-food": BowlFood,
  "chef-hat": ChefHat,
  hamburger: Hamburger,
  pizza: Pizza,
  bread: Bread,
  egg: Egg,
  "egg-crack": EggCrack,
  popcorn: Popcorn,
  tray: Tray,
  knife: Knife,
  "call-bell": CallBell,
  flame: Flame,
  fire: Fire,
  shrimp: Shrimp,
  fish: Fish,
  "fish-simple": FishSimple,
  waves: Waves,
  "tree-palm": TreePalm,
  cow: Cow,
  bird: Bird,
  cheese: Cheese,
  avocado: Avocado,
  carrot: Carrot,
  pepper: Pepper,
  leaf: Leaf,
  plant: Plant,
  grains: Grains,
  orange: Orange,
  "orange-slice": OrangeSlice,
  cherries: Cherries,
  jar: Jar,
  "jar-label": JarLabel,
  cake: Cake,
  "ice-cream": IceCream,
  popsicle: Popsicle,
  cookie: Cookie,
  wine: Wine,
  champagne: Champagne,
  martini: Martini,
  brandy: Brandy,
  "beer-stein": BeerStein,
  "beer-bottle": BeerBottle,
  "pint-glass": PintGlass,
  coffee: Coffee,
  "coffee-bean": CoffeeBean,
  "tea-bag": TeaBag,
  drop: Drop,
  snowflake: Snowflake,
  flask: Flask,
  star: Star,
  sparkle: Sparkle,
  crown: Crown,
  heart: Heart,
  gift: Gift,
  baby: Baby,
  sun: Sun,
};

export function CategoryGlyph({
  icon,
  className,
  weight = "regular",
}: {
  icon: CategoryIconId;
  className?: string;
  weight?: "regular" | "bold" | "fill" | "duotone";
}) {
  const Icon = CATEGORY_ICON_COMPONENTS[icon] ?? CookingPot;
  return <Icon className={className} weight={weight} />;
}
